package com.linearlite.server.entity;

import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableName;
import java.time.LocalDateTime;

@TableName("codex_runs")
public class CodexRun {
    @TableId private String id;
    private String clientRequestId; private Long taskId; private String taskKey; private LocalDateTime taskUpdatedAt; private String taskSnapshot; private String dispatchInstruction; private Long createdBy; private Long runnerId; private Long repositoryId; @TableField(exist = false) private String repositoryKey; private String baseBranch; private String branchName; private String codexThreadId; private String status; private LocalDateTime leaseExpiresAt; private LocalDateTime cancelRequestedAt; private String resultSummary; private String resultPayload; private String errorCode; private String errorMessage; private LocalDateTime createdAt; private LocalDateTime claimedAt; private LocalDateTime startedAt; private LocalDateTime finishedAt;
    public String getId(){return id;} public void setId(String v){id=v;} public String getClientRequestId(){return clientRequestId;} public void setClientRequestId(String v){clientRequestId=v;} public Long getTaskId(){return taskId;} public void setTaskId(Long v){taskId=v;} public String getTaskKey(){return taskKey;} public void setTaskKey(String v){taskKey=v;} public LocalDateTime getTaskUpdatedAt(){return taskUpdatedAt;} public void setTaskUpdatedAt(LocalDateTime v){taskUpdatedAt=v;} public String getTaskSnapshot(){return taskSnapshot;} public void setTaskSnapshot(String v){taskSnapshot=v;} public String getDispatchInstruction(){return dispatchInstruction;} public void setDispatchInstruction(String v){dispatchInstruction=v;} public Long getCreatedBy(){return createdBy;} public void setCreatedBy(Long v){createdBy=v;} public Long getRunnerId(){return runnerId;} public void setRunnerId(Long v){runnerId=v;} public Long getRepositoryId(){return repositoryId;} public void setRepositoryId(Long v){repositoryId=v;} public String getRepositoryKey(){return repositoryKey;} public void setRepositoryKey(String v){repositoryKey=v;} public String getBaseBranch(){return baseBranch;} public void setBaseBranch(String v){baseBranch=v;} public String getBranchName(){return branchName;} public void setBranchName(String v){branchName=v;} public String getCodexThreadId(){return codexThreadId;} public void setCodexThreadId(String v){codexThreadId=v;} public String getStatus(){return status;} public void setStatus(String v){status=v;} public LocalDateTime getLeaseExpiresAt(){return leaseExpiresAt;} public void setLeaseExpiresAt(LocalDateTime v){leaseExpiresAt=v;} public LocalDateTime getCancelRequestedAt(){return cancelRequestedAt;} public void setCancelRequestedAt(LocalDateTime v){cancelRequestedAt=v;} public String getResultSummary(){return resultSummary;} public void setResultSummary(String v){resultSummary=v;} public String getResultPayload(){return resultPayload;} public void setResultPayload(String v){resultPayload=v;} public String getErrorCode(){return errorCode;} public void setErrorCode(String v){errorCode=v;} public String getErrorMessage(){return errorMessage;} public void setErrorMessage(String v){errorMessage=v;} public LocalDateTime getCreatedAt(){return createdAt;} public void setCreatedAt(LocalDateTime v){createdAt=v;} public LocalDateTime getClaimedAt(){return claimedAt;} public void setClaimedAt(LocalDateTime v){claimedAt=v;} public LocalDateTime getStartedAt(){return startedAt;} public void setStartedAt(LocalDateTime v){startedAt=v;} public LocalDateTime getFinishedAt(){return finishedAt;} public void setFinishedAt(LocalDateTime v){finishedAt=v;}
}
