package com.linearlite.server.controller;
import com.linearlite.server.common.ApiResponse; import com.linearlite.server.dto.codex.CodexDtos; import com.linearlite.server.entity.CodexRun; import com.linearlite.server.entity.CodexRunEvent; import com.linearlite.server.filter.JwtAuthFilter; import com.linearlite.server.service.CodexDispatchService; import jakarta.servlet.http.HttpServletRequest; import org.springframework.http.ResponseEntity; import org.springframework.web.bind.annotation.*; import java.util.List;
@RestController public class CodexRunController { private final CodexDispatchService service; public CodexRunController(CodexDispatchService service){this.service=service;}
 @PostMapping("/api/tasks/{taskKey}/codex-runs") public ResponseEntity<ApiResponse<CodexRun>> dispatch(HttpServletRequest r,@PathVariable String taskKey,@RequestBody CodexDtos.DispatchRequest b){return ResponseEntity.ok(ApiResponse.success(service.dispatch(taskKey,user(r),b)));}
 @GetMapping("/api/tasks/{taskKey}/codex-runs") public ResponseEntity<ApiResponse<List<CodexRun>>> list(HttpServletRequest r,@PathVariable String taskKey){return ResponseEntity.ok(ApiResponse.success(service.listTaskRuns(taskKey,user(r))));}
 @GetMapping("/api/codex-runs/{runId}") public ResponseEntity<ApiResponse<CodexRun>> get(HttpServletRequest r,@PathVariable String runId){return ResponseEntity.ok(ApiResponse.success(service.getRun(runId,user(r))));}
 @GetMapping("/api/codex-runs/{runId}/events") public ResponseEntity<ApiResponse<List<CodexRunEvent>>> events(HttpServletRequest r,@PathVariable String runId,@RequestParam(required=false) Long afterSequence){return ResponseEntity.ok(ApiResponse.success(service.events(runId,user(r),afterSequence)));}
 @PostMapping("/api/codex-runs/{runId}/messages") public ResponseEntity<ApiResponse<Void>> message(HttpServletRequest r,@PathVariable String runId,@RequestBody CodexDtos.MessageRequest b){service.sendMessage(runId,user(r),b);return ResponseEntity.ok(ApiResponse.success());}
 @PostMapping("/api/codex-runs/{runId}/cancel") public ResponseEntity<ApiResponse<Void>> cancel(HttpServletRequest r,@PathVariable String runId){service.cancel(runId,user(r));return ResponseEntity.ok(ApiResponse.success());}
 private Long user(HttpServletRequest r){return (Long)r.getAttribute(JwtAuthFilter.REQUEST_ATTR_USER_ID);}
}
