package com.linearlite.server.controller;
import com.linearlite.server.common.ApiResponse; import com.linearlite.server.dto.codex.CodexDtos; import com.linearlite.server.entity.CodexRun; import com.linearlite.server.filter.CodexRunnerAuthFilter; import com.linearlite.server.service.CodexDispatchService; import jakarta.servlet.http.HttpServletRequest; import org.springframework.http.ResponseEntity; import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/api/codex-runner") public class CodexRunnerAgentController { private final CodexDispatchService service; public CodexRunnerAgentController(CodexDispatchService service){this.service=service;}
 @PostMapping("/register") public ResponseEntity<ApiResponse<CodexDtos.RegisterResponse>> register(@RequestBody CodexDtos.RegisterRequest b){return ResponseEntity.ok(ApiResponse.success(service.register(b)));}
 @PutMapping("/heartbeat") public ResponseEntity<ApiResponse<Void>> heartbeat(HttpServletRequest r,@RequestBody CodexDtos.HeartbeatRequest b){service.heartbeat(id(r),b);return ResponseEntity.ok(ApiResponse.success());}
 @PostMapping("/runs/claim") public ResponseEntity<ApiResponse<CodexRun>> claim(HttpServletRequest r){return ResponseEntity.ok(ApiResponse.success(service.claim(id(r))));}
 @PutMapping("/runs/{runId}/lease") public ResponseEntity<ApiResponse<Void>> lease(HttpServletRequest r,@PathVariable String runId){service.renewLease(runId,id(r));return ResponseEntity.ok(ApiResponse.success());}
 @PutMapping("/runs/{runId}/started") public ResponseEntity<ApiResponse<Void>> started(HttpServletRequest r,@PathVariable String runId){service.markDesktopSessionStarted(runId,id(r));return ResponseEntity.ok(ApiResponse.success());}
 @PostMapping("/runs/{runId}/events") public ResponseEntity<ApiResponse<Void>> event(HttpServletRequest r,@PathVariable String runId,@RequestBody CodexDtos.EventRequest b){service.event(runId,id(r),b);return ResponseEntity.ok(ApiResponse.success());}
 @PostMapping("/runs/{runId}/needs-input") public ResponseEntity<ApiResponse<Void>> needsInput(HttpServletRequest r,@PathVariable String runId,@RequestBody CodexDtos.MessageRequest b){service.needsInput(runId,id(r),b.content());return ResponseEntity.ok(ApiResponse.success());}
 @PostMapping("/runs/{runId}/messages/claim") public ResponseEntity<ApiResponse<CodexDtos.RunnerMessageResponse>> message(HttpServletRequest r,@PathVariable String runId){return ResponseEntity.ok(ApiResponse.success(service.claimMessage(runId,id(r))));}
 @PutMapping("/runs/{runId}/messages/{messageId}/consumed") public ResponseEntity<ApiResponse<Void>> consumed(HttpServletRequest r,@PathVariable String runId,@PathVariable Long messageId){service.consumeMessage(runId,id(r),messageId);return ResponseEntity.ok(ApiResponse.success());}
 @PostMapping("/runs/{runId}/complete") public ResponseEntity<ApiResponse<Void>> complete(HttpServletRequest r,@PathVariable String runId,@RequestBody CodexDtos.CompleteRequest b){service.complete(runId,id(r),b);return ResponseEntity.ok(ApiResponse.success());}
 private Long id(HttpServletRequest r){return (Long)r.getAttribute(CodexRunnerAuthFilter.REQUEST_ATTR_RUNNER_ID);}
}
